---
title: "predicting memory performance"
author: "Adam Dede"
date: "2024-07-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages and set up environment

```{r message = FALSE, warning = FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE)

# load packages
library(tidyverse)
library(RColorBrewer)
library(hrbrthemes)
library(lme4)
# library(lmerOut)
library(lmerTest)
library(car)
library(ggeffects)
library(emmeans)
library(effects)

# set contrasts
options(contrasts=c("contr.Sum","contr.Helmert"))
options(decorate.contr.Sum="",decorate.contrasts=c("[","]"))

```

## Read in data frame

```{r load data}

# load in main data frame
df <- read.csv("R:\\MSS\\Johnson_Lab\\dtf8829\\GitHub\\HpcAccConnectivityProject\\allSig.csv", header = T)


```

## reformat into better format

```{r demo stats}

longDF <- df %>% pivot_longer(cols = -all_of(c('subID', 'sex', 'age', 'memAcc', 
                                               'memD', 'reg', 'encHIT', 
                                               'encMISS', 'retHIT', 'retMISS')),
                              names_to = c('type', 'regionphase'), 
                              names_pattern = "^([^_]+)(.*)$",
                              values_to = 'stat'
                              ) %>%
          filter(!is.nan(stat))

longDF1 <- filter(longDF, type == 'ppc')
longDF2 <- filter(longDF, type != 'ppc')
longDF1$HFB = grepl('HFB', longDF1$regionphase)
longDF2$HFB = grepl('peak', longDF2$type)

longDF <- rbind(longDF1, longDF2)


longDF <- longDF %>% 
  filter(reg == "mtl" | reg == "hip" | reg == "acc" | 
         reg == "dlPFC" | reg == "pPFC")


test <- longDF %>% group_by(type, regionphase, HFB) %>%
  summarize(corVal = cor(memAcc, stat), 
            count = n()) 
test = test[test$count>8,]


df_hist <- test %>%
  group_by(HFB) %>%
  mutate(bin = cut(corVal, breaks = seq(-1,1,.2))) %>%  # You can adjust the number of breaks
  count(HFB, bin) %>%
  group_by(HFB) %>%
  mutate(proportion = n / sum(n))

# Plot the histogram with proportions
ggplot(df_hist, aes(x = bin, y = proportion, fill = HFB)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(y = "Proportion", x = "Value", title = "Histogram Scaled to Within-Group Proportion") +
  theme_minimal() +
  facet_wrap(~ group, scales = "free_x")


longDF %>% filter(reg == "hip", type == "imageITPC", regionphase=="_hip_sub1") %>% ggplot(aes(x = stat, y = memD)) + geom_point()


age.lm = lm(age ~ as.factor(reg), data = df)
summary(age.lm)

sex.glm = glm(as.factor(sex) ~ as.factor(reg), family = binomial,  data = df)
summary(sex.glm)

memAcc.lm = lm(memAcc ~ as.factor(reg), data = df)
summary(memAcc.lm)

memD.lm = lm(memD ~ as.factor(reg), data = df)
summary(memD.lm)


```

## summarize table

```{r table}

df %>% group_by(reg) %>% summarize(N = n(), 
                                   Fem = sum(sex == "F"),
                                   agemean = mean(age), 
                                   agesd = sd(age),
                                   memAccmean = mean(memAcc),  
                                   memAccsd = sd(memAcc),
                                   memDmean = mean(memD), 
                                   memDsd = sd(memD),
                                   encHitmean = mean(encHIT),
                                   encHitsd = sd(encHIT),
                                   encMissmean = mean(encMISS),
                                   encMisssd = sd(encMISS),
                                   retHitmean = mean(retHIT),
                                   retHitsd = sd(retHIT),
                                   retMissmean = mean(retMISS),
                                   retMisssd = sd(retMISS) )

```
