---
title: "demographic analysis"
author: "Adam Dede"
date: "2024-07-12"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages and set up environment

```{r message = FALSE, warning = FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE)

# load packages
library(tidyverse)
library(RColorBrewer)
library(hrbrthemes)
library(lme4)
# library(lmerOut)
library(lmerTest)
library(car)
library(ggeffects)
library(emmeans)
library(effects)

# set contrasts
options(contrasts=c("contr.Sum","contr.Helmert"))
options(decorate.contr.Sum="",decorate.contrasts=c("[","]"))

```

## Read in data frame

```{r load data}

# load in main data frame
df <- read.csv("R:\\MSS\\Johnson_Lab\\dtf8829\\GitHub\\HpcAccConnectivityProject\\demographics.csv", header = T)


```

## stats to test for variability between regions on key metrics

```{r demo stats}

age.lm = lm(age ~ as.factor(reg), data = df)
summary(age.lm)

sex.glm = glm(as.factor(sex) ~ as.factor(reg), family = binomial,  data = df)
summary(sex.glm)

memAcc.lm = lm(memAcc ~ as.factor(reg), data = df)
summary(memAcc.lm)

memD.lm = lm(memD ~ as.factor(reg), data = df)
summary(memD.lm)


```


