---
title: "Adam's Analysis"
author: "Zachariah Cross & Adam Dede"
date: "2023-10-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages and set up environment

```{r message = FALSE, warning = FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE)

# load packages
library(tidyverse)
library(RColorBrewer)
library(hrbrthemes)
library(lme4)
# library(lmerOut)
library(lmerTest)
library(car)
library(ggeffects)
library(emmeans)
library(effects)

# set contrasts
options(contrasts=c("contr.Sum","contr.Helmert"))
options(decorate.contr.Sum="",decorate.contrasts=c("[","]"))

```

## Read in data frame

```{r load data}

# load in main data frame
df <- read.csv("R:\\MSS\\Johnson_Lab\\dtf8829\\GitHub\\HpcAccConnectivityProject\\graphDat.csv", header = T)
setwd('G:\\My Drive\\Johnson\\MTL_PFC_networkFigs\\Rfigs')
# factorise variables
df$realID = paste(df$subID, '_', df$chi, '_', df$timeSet, '_', df$time, sep = '')
df <- df %>% 
  distinct(realID, .keep_all = TRUE)
df$realID = paste(df$subID, '_', df$chi, sep = '')

df <- df %>% filter(reg1 != 'acc')

df <- df %>%
  mutate(subID= as.factor(subID),
         encRet = as.factor(encRet),
         reg1 = as.factor(reg1),
         reg2 = as.factor(reg2),
         chi = as.factor(chi))



long_df <- pivot_longer(
  df,
  cols = c(hitBC, missBC, hitST, missST, 
           hitSaturation, missSaturation, 
           hitEff, missEff,
           hitChar, missChar),
  names_to = c("hitMiss", ".value"),
  names_pattern = "(hit|miss)(.*)"
)

df$BCdif = df$hitBC - df$missBC
df$STdif = df$hitST - df$missST
df$SATdif = df$hitSaturation - df$missSaturation
df$charDif = df$hitChar - df$missChar

```

## encoding characteristic mean vector length

```{r char encode}

reg_order <- c("hip", "mtl", "acc", "dlPFC", "pPFC")
# Color data frame in R
regColors <- data.frame(
  parahip = rgb(214, 77, 97, maxColorValue = 255),       # dark pink
  dlPFC = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  iTemp = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  lTemp = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  polarPFC = rgb(51, 102, 153, maxColorValue = 255),     # lilac
  visual = rgb(132, 125, 212, maxColorValue = 255),      # lilac
  ACC = rgb(204, 153, 204, maxColorValue = 255),         # dark red
  PCC = rgb(184, 78, 83, maxColorValue = 255),          # dark red
  Hip = rgb(61, 187, 218, maxColorValue = 255)           # dusky blue
)

long_df$reg1 = factor(long_df$reg1, reg_order)


#region by region? hip: 
charModel <- lmer(Char ~  reg1 * timeSet * hitMiss + (1|realID), 
                     data = filter(long_df, encRet == 'enc'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

charModel <- lmer(Char ~  reg1 * timeSet + (1|realID), 
                     data = filter(long_df, encRet == 'enc', hitMiss == 'hit'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

emmeans(charModel, pairwise ~ reg1 * timeSet , type="response", adjust = "holm")

charModel <- lmer(Char ~  reg1 * timeSet + (1|realID), 
                     data = filter(long_df, encRet == 'enc', hitMiss == 'miss'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

emmeans(charModel, pairwise ~ reg1 * timeSet , type="response", adjust = "holm")

write.csv(filter(long_df, encRet == 'enc', hitMiss == 'hit'), 'testDat.csv')


long_df %>% filter(encRet == 'enc', hitMiss == 'hit') %>%
  ggplot(aes( fill = timeSet, color = timeSet, y = Char, x = reg1)) + 
    geom_boxplot(outlier.shape = NA, alpha = .75, 
                 position = position_dodge(.85)) +
    geom_jitter(show.legend = F, shape = 21, size = 4, 
                position = position_jitterdodge(dodge.width = .85, 
                                                jitter.width = .2)) + 
    scale_fill_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
    scale_color_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
  theme_classic() +
  ylim(c(0,50)) + 
    theme(axis.line = element_line(color = 'black', linewidth = 3),
          axis.ticks = element_line(colour = "black", linewidth = 2),
          axis.ticks.length=unit(-.25, "cm"),
          text = element_text(size = 20),
          legend.position = 'none',
          axis.text.x = element_text(margin = margin(t = 10)),
          axis.text.y = element_text(margin = margin(r = 10))) 


  
long_df %>% filter(encRet == 'enc', hitMiss == 'miss') %>%
  ggplot(aes( fill = timeSet, color = timeSet, y = Char, x = reg1)) + 
    geom_boxplot(outlier.shape = NA, alpha = .75, 
                 position = position_dodge(.85)) +
    geom_jitter(show.legend = F, shape = 21, size = 4, 
                position = position_jitterdodge(dodge.width = .85, 
                                                jitter.width = .2)) + 
    scale_fill_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
    scale_color_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
  theme_classic() +
  ylim(c(0,50)) + 
    theme(axis.line = element_line(color = 'black', linewidth = 3),
          axis.ticks = element_line(colour = "black", linewidth = 2),
          axis.ticks.length=unit(-.25, "cm"),
          text = element_text(size = 20),
          legend.position = 'none',
          axis.text.x = element_text(margin = margin(t = 10)),
          axis.text.y = element_text(margin = margin(r = 10))) 

```
## characteristic mean vector length retrieval 

```{r char retrieve}
reg_order <- c("hip", "mtl", "acc", "dlPFC", "pPFC")
# Color data frame in R
regColors <- data.frame(
  parahip = rgb(214, 77, 97, maxColorValue = 255),       # dark pink
  dlPFC = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  iTemp = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  lTemp = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  polarPFC = rgb(51, 102, 153, maxColorValue = 255),     # lilac
  visual = rgb(132, 125, 212, maxColorValue = 255),      # lilac
  ACC = rgb(204, 153, 204, maxColorValue = 255),         # dark red
  PCC = rgb(184, 78, 83, maxColorValue = 255),          # dark red
  Hip = rgb(61, 187, 218, maxColorValue = 255)           # dusky blue
)

long_df$reg1 = factor(long_df$reg1, reg_order)


#region by region? hip: 
charModel <- lmer(Char ~  reg1 * timeSet * hitMiss + (1|realID), 
                     data = filter(long_df, encRet == 'ret'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

charModel <- lmer(Char ~  reg1 * timeSet + (1|realID), 
                     data = filter(long_df, encRet == 'ret', hitMiss == 'hit'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

emmeans(charModel, pairwise ~ reg1 * timeSet , type="response", adjust = "holm")

charModel <- lmer(Char ~  reg1 * timeSet + (1|realID), 
                     data = filter(long_df, encRet == 'ret', hitMiss == 'miss'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

emmeans(charModel, pairwise ~ reg1 * timeSet , type="response", adjust = "holm")



long_df %>% filter(encRet == 'ret', hitMiss == 'hit') %>%
  ggplot(aes( fill = timeSet, color = timeSet, y = Char, x = reg1)) + 
    geom_boxplot(outlier.shape = NA, alpha = .75, 
                 position = position_dodge(.85)) +
    geom_jitter(show.legend = F, shape = 21, size = 4, 
                position = position_jitterdodge(dodge.width = .85, 
                                                jitter.width = .2)) + 
    scale_fill_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
    scale_color_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
  theme_classic() +
  ylim(c(0,50)) + 
    theme(axis.line = element_line(color = 'black', linewidth = 3),
          axis.ticks = element_line(colour = "black", linewidth = 2),
          axis.ticks.length=unit(-.25, "cm"),
          text = element_text(size = 20),
          legend.position = 'none',
          axis.text.x = element_text(margin = margin(t = 10)),
          axis.text.y = element_text(margin = margin(r = 10))) 


  
long_df %>% filter(encRet == 'ret', hitMiss == 'miss') %>%
  ggplot(aes( fill = timeSet, color = timeSet, y = Char, x = reg1)) + 
    geom_boxplot(outlier.shape = NA, alpha = .75, 
                 position = position_dodge(.85)) +
    geom_jitter(show.legend = F, shape = 21, size = 4, 
                position = position_jitterdodge(dodge.width = .85, 
                                                jitter.width = .2)) + 
    scale_fill_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
    scale_color_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
  theme_classic() +
  ylim(c(0,50)) + 
    theme(axis.line = element_line(color = 'black', linewidth = 3),
          axis.ticks = element_line(colour = "black", linewidth = 2),
          axis.ticks.length=unit(-.25, "cm"),
          text = element_text(size = 20),
          legend.position = 'none',
          axis.text.x = element_text(margin = margin(t = 10)),
          axis.text.y = element_text(margin = margin(r = 10))) 


```

## encoding strength mean vector length

```{r strength encode}

reg_order <- c("hip", "mtl", "acc", "dlPFC", "pPFC")
# Color data frame in R
regColors <- data.frame(
  parahip = rgb(214, 77, 97, maxColorValue = 255),       # dark pink
  dlPFC = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  iTemp = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  lTemp = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  polarPFC = rgb(51, 102, 153, maxColorValue = 255),     # lilac
  visual = rgb(132, 125, 212, maxColorValue = 255),      # lilac
  ACC = rgb(204, 153, 204, maxColorValue = 255),         # dark red
  PCC = rgb(184, 78, 83, maxColorValue = 255),          # dark red
  Hip = rgb(61, 187, 218, maxColorValue = 255)           # dusky blue
)

long_df$reg1 = factor(long_df$reg1, reg_order)


#region by region? hip: 
charModel <- lmer(ST ~  reg1 * timeSet * hitMiss + (1|realID), 
                     data = filter(long_df, encRet == 'enc'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

charModel <- lmer(ST ~  reg1 * timeSet + (1|realID), 
                     data = filter(long_df, encRet == 'enc', hitMiss == 'hit'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

emmeans(charModel, pairwise ~ reg1 * timeSet , type="response", adjust = "holm")

charModel <- lmer(ST ~  reg1 * timeSet + (1|realID), 
                     data = filter(long_df, encRet == 'enc', hitMiss == 'miss'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

emmeans(charModel, pairwise ~ reg1 * timeSet , type="response", adjust = "holm")




long_df %>% filter(encRet == 'enc', hitMiss == 'hit') %>%
  ggplot(aes( fill = timeSet, color = timeSet, y = ST, x = reg1)) + 
    geom_boxplot(outlier.shape = NA, alpha = .75, 
                 position = position_dodge(.85)) +
    geom_jitter(show.legend = F, shape = 21, size = 4, 
                position = position_jitterdodge(dodge.width = .85, 
                                                jitter.width = .2)) + 
    scale_fill_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
    scale_color_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
  theme_classic() +
  ylim(c(0,.2)) + 
    theme(axis.line = element_line(color = 'black', linewidth = 3),
          axis.ticks = element_line(colour = "black", linewidth = 2),
          axis.ticks.length=unit(-.25, "cm"),
          text = element_text(size = 20),
          legend.position = 'none',
          axis.text.x = element_text(margin = margin(t = 10)),
          axis.text.y = element_text(margin = margin(r = 10))) 


  
long_df %>% filter(encRet == 'enc', hitMiss == 'miss') %>%
  ggplot(aes( fill = timeSet, color = timeSet, y = ST, x = reg1)) + 
    geom_boxplot(outlier.shape = NA, alpha = .75, 
                 position = position_dodge(.85)) +
    geom_jitter(show.legend = F, shape = 21, size = 4, 
                position = position_jitterdodge(dodge.width = .85, 
                                                jitter.width = .2)) + 
    scale_fill_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
    scale_color_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
  theme_classic() +
  ylim(c(0,.2)) + 
    theme(axis.line = element_line(color = 'black', linewidth = 3),
          axis.ticks = element_line(colour = "black", linewidth = 2),
          axis.ticks.length=unit(-.25, "cm"),
          text = element_text(size = 20),
          legend.position = 'none',
          axis.text.x = element_text(margin = margin(t = 10)),
          axis.text.y = element_text(margin = margin(r = 10))) 

```
## characteristic mean vector length retrieval 

```{r char retrieve}
reg_order <- c("hip", "mtl", "acc", "dlPFC", "pPFC")
# Color data frame in R
regColors <- data.frame(
  parahip = rgb(214, 77, 97, maxColorValue = 255),       # dark pink
  dlPFC = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  iTemp = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  lTemp = rgb(145, 162, 80, maxColorValue = 255),        # light forest green
  polarPFC = rgb(51, 102, 153, maxColorValue = 255),     # lilac
  visual = rgb(132, 125, 212, maxColorValue = 255),      # lilac
  ACC = rgb(204, 153, 204, maxColorValue = 255),         # dark red
  PCC = rgb(184, 78, 83, maxColorValue = 255),          # dark red
  Hip = rgb(61, 187, 218, maxColorValue = 255)           # dusky blue
)

long_df$reg1 = factor(long_df$reg1, reg_order)


#region by region? hip: 
charModel <- lmer(Char ~  reg1 * timeSet * hitMiss + (1|realID), 
                     data = filter(long_df, encRet == 'ret'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

charModel <- lmer(Char ~  reg1 * timeSet + (1|realID), 
                     data = filter(long_df, encRet == 'ret', hitMiss == 'hit'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

emmeans(charModel, pairwise ~ reg1 * timeSet , type="response", adjust = "holm")

charModel <- lmer(Char ~  reg1 * timeSet + (1|realID), 
                     data = filter(long_df, encRet == 'ret', hitMiss == 'miss'), 
            control = lmerControl(optimizer = "bobyqa"))
summary(charModel)
Anova(charModel)

emmeans(charModel, pairwise ~ reg1 * timeSet , type="response", adjust = "holm")



long_df %>% filter(encRet == 'ret', hitMiss == 'hit') %>%
  ggplot(aes( fill = timeSet, color = timeSet, y = Char, x = reg1)) + 
    geom_boxplot(outlier.shape = NA, alpha = .75, 
                 position = position_dodge(.85)) +
    geom_jitter(show.legend = F, shape = 21, size = 4, 
                position = position_jitterdodge(dodge.width = .85, 
                                                jitter.width = .2)) + 
    scale_fill_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
    scale_color_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
  theme_classic() +
  ylim(c(0,50)) + 
    theme(axis.line = element_line(color = 'black', linewidth = 3),
          axis.ticks = element_line(colour = "black", linewidth = 2),
          axis.ticks.length=unit(-.25, "cm"),
          text = element_text(size = 20),
          legend.position = 'none',
          axis.text.x = element_text(margin = margin(t = 10)),
          axis.text.y = element_text(margin = margin(r = 10))) 


  
long_df %>% filter(encRet == 'ret', hitMiss == 'miss') %>%
  ggplot(aes( fill = timeSet, color = timeSet, y = Char, x = reg1)) + 
    geom_boxplot(outlier.shape = NA, alpha = .75, 
                 position = position_dodge(.85)) +
    geom_jitter(show.legend = F, shape = 21, size = 4, 
                position = position_jitterdodge(dodge.width = .85, 
                                                jitter.width = .2)) + 
    scale_fill_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
    scale_color_manual(values=c( "#E1C271", "#3BACDD"),
                      labels=c(  'HFB', 'Image')) +  
  theme_classic() +
  ylim(c(0,50)) + 
    theme(axis.line = element_line(color = 'black', linewidth = 3),
          axis.ticks = element_line(colour = "black", linewidth = 2),
          axis.ticks.length=unit(-.25, "cm"),
          text = element_text(size = 20),
          legend.position = 'none',
          axis.text.x = element_text(margin = margin(t = 10)),
          axis.text.y = element_text(margin = margin(r = 10))) 


```



